import re

EMAIL_AVAILABILITY_IDENTIFIER = u'res-id: {0}'
EMAIL_AVAILABILITY_IDENTIFIER_PATTERN = r'res-id:\s*(\d+)'
EMAIL_AVAILABILITY_IDENTIFIER_RE = re.compile(EMAIL_AVAILABILITY_IDENTIFIER_PATTERN, flags=re.I | re.M)
